### ISSUE TITLE
How to configure my.cnf

### ISSUE THREAD

**Issue by Vacilando** [dockerizedrupal/docker-mysql#11]
Setting up the multibyte support for Drupal we need to add a few lines to my.cnf -- see http://www.jeffgeerling.com/blog/2016/getting-emoji-and-multibyte-characters-on-your-drupal-7-site-750

Can this be done in docker-compose.yml and how?

**Comment by Vacilando** [comment]
Any news on this? I have a number of utf8mb4-encoded databases which are impossible to import to dockerizedrupal without this.

**Comment by Niklan** [comment]
Same story here. I found how to edit my.cnf

`docker exec -it MYSQL_CONTAINER_ID bash`
`nano /etc/mysql/my.cnf`

Seems to solve my problem.

**Comment by Vacilando** [comment]
@Niklan -- did that as well, but I think such change is not permanent, unfortunately.

**Comment by Niklan** [comment]
@Vacilando for me it still working after restart, i think new version of docker container can broke this, but until it will work.

**Comment by viljaste** [comment]
Hey guys, MySQL image version 2.0.1 should now support this by default.

**Comment by viljaste** [comment]
Closing this as this project is unfortunately not active anymore.
